Pandas
======

- Provides a powerful `DataFrame` object.
- Makes it easy to deal with "Tabular" data.
- Very easy to read, process and visualize data.
- See http://pandas.pydata.org

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

Fundamentals
--------------

- Why do we need this?
- Data is often **tabular**
  - Imagine this class data!
  - Each student has data values

- Think of each student as a row
- Each column as an attribute
- So the columns are **aligned** using the row

- With `pandas`, data alignment is **central**

Building block: `Series`
-----------

- "Labels" are collectively called the **index**

- `Series`: bundles together an index and values
- Index can be implicit or explicit


In [3]:
s = pd.Series(np.random.randn(5))
s

0   -0.015407
1   -0.965222
2   -0.649931
3   -0.147824
4   -1.941011
dtype: float64

In [4]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a   -1.701888
b   -0.335510
c   -0.026161
d    0.610543
e   -0.456729
dtype: float64

`Series`: some points to note
---------

- They behave like `numpy` arrays or dicts
- But carry the index
- All operations align on the label (i.e. index)
- Unaligned series will use the union of indices
- `NaN` is used to refer to missing values


In [5]:
a = pd.Series(np.ones(5), index=["a", "b", "c", "d", "e"])
b = pd.Series(np.arange(5), index=["e", "d", "c", "b", "a"])
a + b

a    5.0
b    4.0
c    3.0
d    2.0
e    1.0
dtype: float64

In [6]:
a.dtype

dtype('float64')

In [7]:
a = pd.Series(np.ones(5), index=["a", "b", "c", "d", "e"])
b = pd.Series(np.arange(4), index=["e", "d", "c", "b"])
a + b

a    NaN
b    4.0
c    3.0
d    2.0
e    1.0
dtype: float64

- Works with repeated labels too

In [8]:
a = pd.Series(np.ones(5), index=["a", "b", "c", "d", "e"])
b = pd.Series(np.arange(5), index=["a", "d", "c", "b", 'a'])
a + b

a    1.0
a    5.0
b    4.0
c    3.0
d    2.0
e    NaN
dtype: float64

In [10]:
c = a + b

a    2.0
a    6.0
b    5.0
c    4.0
d    3.0
e    NaN
dtype: float64

Aside
-------

- `NaN` is a number!
- Beware of them

In [11]:
float('nan'), float('NaN')

(nan, nan)

In [12]:
type(float('nan'))

float

In [14]:
np.nan

nan

In [15]:
x = np.arange(5, dtype=float)
np.sum(x)

np.float64(10.0)

In [16]:
x[0] = np.nan
np.mean(x)

np.float64(nan)

- Use `np.nan*` functions
- `np.isnan` is also handy


In [17]:
np.nansum(x)

np.float64(10.0)

`DataFrame` basics
=======================

- A table of data: a spreadsheet
- Same index for all columns
- Different data types per column



In [18]:
x = np.linspace(0, 2*np.pi, 100)
sin = np.sin(x)
cos = np.cos(x)

In [25]:
j = pd.DataFrame(dict(x=[1, 2, 3], y=['hello', 'class', '2025']))

In [26]:
j.describe()

x
count  3.0
mean   2.0
std    1.0
min    1.0
25%    1.5
50%    2.0
75%    2.5
max    3.0

In [27]:
dict(a=[1, 2, 3], b='Hello')

{'a': [1, 2, 3], 'b': 'Hello'}

In [42]:
j.dtypes

x     int64
y    object
dtype: object

In [28]:
df = pd.DataFrame({'x': x, 'sin': sin, 'cos': cos, 'x-data':x})
# OR
#df = pd.DataFrame(dict(x=x, sin=sin, cos=cos))

In [29]:
df.head() # or df.tail()

x       sin       cos    x-data
0  0.000000  0.000000  1.000000  0.000000
1  0.063467  0.063424  0.997987  0.063467
2  0.126933  0.126592  0.991955  0.126933
3  0.190400  0.189251  0.981929  0.190400
4  0.253866  0.251148  0.967949  0.253866

In [30]:
df.tail()

x           sin       cos    x-data
95  6.029319 -2.511480e-01  0.967949  6.029319
96  6.092786 -1.892512e-01  0.981929  6.092786
97  6.156252 -1.265925e-01  0.991955  6.156252
98  6.219719 -6.342392e-02  0.997987  6.219719
99  6.283185 -2.449294e-16  1.000000  6.283185

In [31]:
df.describe()

x           sin         cos      x-data
count  100.000000  1.000000e+02  100.000000  100.000000
mean     3.141593 -1.244130e-17    0.010000    3.141593
std      1.841258  7.071068e-01    0.714143    1.841258
min      0.000000 -9.998741e-01   -0.999497    0.000000
25%      1.570796 -6.957328e-01   -0.701475    1.570796
50%      3.141593 -1.224647e-16    0.015858    3.141593
75%      4.712389  6.957328e-01    0.723734    4.712389
max      6.283185  9.998741e-01    1.000000    6.283185

In [45]:
df.x[10] = 30000

/tmp/ipykernel_793286/120360617.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.x[10] = 30000


In [46]:
df1 = df[10:13]
df1.head()

x       sin       cos    x-data
10  30000.000000  0.592908  0.805270  0.634665
11      0.698132  0.642788  0.766044  0.698132
12      0.761598  0.690079  0.723734  0.761598

In [47]:
df1.x[0] = 3

/tmp/ipykernel_793286/2564291318.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1.x[0] = 3
/tmp/ipykernel_793286/2564291318.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the cave

In [48]:
df.x[10]

np.float64(30000.0)

In [34]:
df['x-data']

0     0.000000
1     0.063467
2     0.126933
3     0.190400
4     0.253866
        ...   
95    6.029319
96    6.092786
97    6.156252
98    6.219719
99    6.283185
Name: x-data, Length: 100, dtype: float64

In [35]:
df.x[::10]

0     0.000000
10    0.634665
20    1.269330
30    1.903996
40    2.538661
50    3.173326
60    3.807991
70    4.442656
80    5.077321
90    5.711987
Name: x, dtype: float64

In [36]:
df1.describe()

x       sin       cos    x-data
count  3.000000  3.000000  3.000000  3.000000
mean   0.698132  0.641925  0.765016  0.698132
std    0.063467  0.048591  0.040778  0.063467
min    0.634665  0.592908  0.723734  0.634665
25%    0.666398  0.617848  0.744889  0.666398
50%    0.698132  0.642788  0.766044  0.698132
75%    0.729865  0.666433  0.785657  0.729865
max    0.761598  0.690079  0.805270  0.761598

In [37]:
# df.x-data[:5] will not work!!
df['x-data'][:5]

0    0.000000
1    0.063467
2    0.126933
3    0.190400
4    0.253866
Name: x-data, dtype: float64

In [38]:
df['x'][:5]

0    0.000000
1    0.063467
2    0.126933
3    0.190400
4    0.253866
Name: x, dtype: float64

In [39]:
df.x[:10]

0    0.000000
1    0.063467
2    0.126933
3    0.190400
4    0.253866
5    0.317333
6    0.380799
7    0.444266
8    0.507732
9    0.571199
Name: x, dtype: float64

In [40]:
df.columns

Index(['x', 'sin', 'cos', 'x-data'], dtype='object')

In [41]:
df.dtypes

x         float64
sin       float64
cos       float64
x-data    float64
dtype: object

In [43]:
len(df)

100

In [44]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [ ]:
df1 = df.copy()
df1.head()

Indexing
=========

Can do what we did above but also using:

- Select column: `df[col]`
- Select row by label: `df.loc[label]`
- Select row by numerical index: `df.iloc[integer]`
- Slice rows: `df[3:13]`
- Select rows by boolean vector: `df[bool_vec]`

Shall explore this below.



In [49]:
df['x']  # Access a column

0     0.000000
1     0.063467
2     0.126933
3     0.190400
4     0.253866
        ...   
95    6.029319
96    6.092786
97    6.156252
98    6.219719
99    6.283185
Name: x, Length: 100, dtype: float64

In [51]:
df.loc[10] = 0.1

In [52]:
j = pd.DataFrame(dict(x=[1, 2, 3], y=['hello', 'class', '2021']), index=list('abc'))

In [53]:
j

x      y
a  1  hello
b  2  class
c  3   2021

In [55]:
j.loc['a']

x        1
y    hello
Name: a, dtype: object

In [56]:
j.iloc[0]

x        1
y    hello
Name: a, dtype: object

In [57]:
j[1:3]

x      y
b  2  class
c  3   2021

- Give me a data frame, where all cosine values are >0.

In [58]:
df.head()

x       sin       cos    x-data
0  0.000000  0.000000  1.000000  0.000000
1  0.063467  0.063424  0.997987  0.063467
2  0.126933  0.126592  0.991955  0.126933
3  0.190400  0.189251  0.981929  0.190400
4  0.253866  0.251148  0.967949  0.253866

In [59]:
y = np.linspace(10, 11, 11)
y

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ])

In [60]:
y > 10.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
y + 1

In [61]:
cond = y > 10.5
y[cond]

array([10.6, 10.7, 10.8, 10.9, 11. ])

- Done with the numpy aside here, back to pandas

In [62]:
condition = df.cos > 0.0
print(len(condition))

100


In [63]:
df_positive_cos = df[condition]
df_positive_cos.describe()

x           sin        cos     x-data
count  50.000000  5.000000e+01  50.000000  50.000000
mean    3.130899 -9.858159e-03   0.636175   3.130899
std     2.460514  6.984454e-01   0.315445   2.460514
min     0.000000 -9.988673e-01   0.047582   0.000000
25%     0.777465 -6.782562e-01   0.371518   0.777465
50%     3.141593 -1.224647e-16   0.701122   3.141593
75%     5.505720  6.782562e-01   0.928368   5.505720
max     6.283185  9.988673e-01   1.000000   6.283185

In [ ]:
# Combining conditionals
cond1 = df.sin > 0.0
df_all_positive = df[condition & cond1]
df_all_positive.describe()

In [ ]:
# Always, always use brackets when combining conditionals with bitwise operations.
df_all_positive = df[(df.cos > 0.0) & (df.sin > 0)]
df_all_positive.describe()

In [ ]:
# Use ~ for inverting the boolean as a Not
c = np.array([True, False, True, False])
c1 = np.array([False, True, False, False])
~(c | c1)

In [ ]:
cond1 = df_positive_cos.sin > 0.0
df_all_positive = df_positive_cos[cond1]
df_all_positive.describe()

In [ ]:
j

In [ ]:
j1 = pd.DataFrame(dict(x=[1, 2, 3, 4], y=['hello', 'class', '2025', 'junk']), 
                 index=list('abcd'))

In [ ]:
j1

In [ ]:
j[j1.x < 2]

In [ ]:
# This adds a new column sincos
df['sincos'] = df.sin*df.cos
len(df.sincos)

In [ ]:
df.describe()

In [ ]:
if 'x-data' in df:
    del df['x-data']
df.head()

Plotting
=========

In [ ]:
df.plot();
# or
#df.plot.line()

Notice that everything is plotted w.r.t. the index!
Let us fix this!

In [ ]:
df.plot.line(x='x', y=['sin', 'cos']);

In [ ]:
# See what this does
df[(df.sin > 0.0) ^ (df.cos < 0.0)].plot.line(x='x', marker='o');

In [ ]:
df.plot.hist(y='cos');
# or
#df.plot(y='cos', kind='hist')

Input and output CSV and other file formats
--------------------------------------------

- `pd.read_csv()`
- `df.to_csv()`
- Can read/save to clip board.
- Directly read from URLs.

In [ ]:
df.to_csv('sincos.csv', index=False)

In [ ]:
df1 = pd.read_csv('sincos.csv')
df1.head()

In [ ]:
%pycat sincos.csv

### Conversion to LaTeX and HTML

In [ ]:
print(df[:5].to_latex())

In [ ]:
print(df[:5].to_latex(index=False))

In [ ]:
print(df[:5].to_html())

In [ ]:
from IPython.display import HTML
HTML(df[:5].to_html())

Selecting from the clipboard
=============================

- Let us select data from our previous sincos:

Select some data and then do this:


In [ ]:
df2 = pd.read_clipboard(sep=',')
df2

In [ ]:
#url = 'https://www.aero.iitb.ac.in/~prabhu/tmp/sslc_small.csv'
url = 'https://drive.google.com/uc?id=1VgrBnWERE9YLslOoCLu8ZFLRbUu4jOED'
df = pd.read_csv(url, sep=';')

In [ ]:
df.head()

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
pd.read_csv?

Exercise
---------


Consider a smaller file:

- File is at: http://www.aero.iitb.ac.in/~prabhu/tmp/sslc_small.csv
- Also in the files section


In [3]:
url = 'http://www.aero.iitb.ac.in/~prabhu/tmp/sslc_small.csv'
df = pd.read_csv(url)
df.head()  # Produces only one strange column of data!

region;roll_number;name;fl;sl;math;sci;ss;total;pass;withheld;extra
0               A;010001;T N;053;036;28;16;44;177;;;                 
1              A;010002;A R;058;037;42;35;40;212;P;;                 
2              A;010003;A M;072;056;71;55;70;324;P;;                 
3              A;010004;S A;087;064;83;58;65;357;P;;                 
4              A;010005;N A;059;045;50;35;48;237;P;;

In [ ]:
df.dtypes

Notice that this data is read incorrectly, this is because the separator is not a comma but a ';' so use this.

In [ ]:
df = pd.read_csv(url, sep=';')
df.head()


In [ ]:
df['region'].value_counts()

In [ ]:
df.plot.scatter(x='fl', y='math');

There are more options to `pd.read_csv`, for example if `'AA'` is a value indicating a non-existing value you can pass an option, called `na_values`.  Read more on the documentation for `read_csv`.

In [5]:
#df = pd.read_csv('sslc1.csv.gz', sep=';', na_values='AA')
url = 'http://www.aero.iitb.ac.in/~prabhu/tmp/sslc1.csv.gz'
df = pd.read_csv(url, sep=';', na_values='AA')
df.head()

region  roll_number             name    sl    fl  math   sci    ss  total  \
0      A        10001  DISMA J SURUTHY  53.0  36.0  28.0  16.0  44.0  177.0   
1      A        10002         PARVIN M  58.0  37.0  42.0  35.0  40.0  212.0   
2      A        10003     MANIKANDAN M  72.0  56.0  71.0  55.0  70.0  324.0   
3      A        10004          PRABU R  87.0  64.0  83.0  58.0  65.0  357.0   
4      A        10005        ARUNRAJ K  59.0  45.0  50.0  35.0  48.0  237.0   

  pass withheld  extra  
0  NaN      NaN    NaN  
1    P      NaN    NaN  
2    P      NaN    NaN  
3    P      NaN    NaN  
4    P      NaN    NaN

In [ ]:
df.describe()

In [ ]:
df.plot.hist(y='sl');

More information
==================

- http://pandas.pydata.org
- Go through the tutorials here:

http://nbviewer.jupyter.org/github/jvns/pandas-cookbook/tree/v0.1/cookbook/

- Go over chapter 1 to 7.